[build]
  publish = "public"
  command = "hugo mod get -u && hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.145.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  GO_VERSION = "1.20"

[context.production.environment]
  HUGO_ENV = "production"

[context.branch-deploy.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404 